/**
 * Tunable user-facing product copy.
 *
 * Keep protocol names, API capabilities, schema identifiers, command flags, and
 * filesystem contract names in the domain code that owns those contracts.
 */
export const copy = {
  common: {
    openFolder: "Open folder",
    copyPath: "Copy path",
    pathCopied: "Path copied.",
    pathCopyFailed: "The path could not be copied.",
    folderOpened: "Folder opened.",
    folderOpenFailed: "The folder could not be opened.",
    resolvingFolder: "Resolving folder…",
    refresh: "Refresh",
    refreshing: "Refreshing…",
    notSet: "Not set",
    planned: "Planned",
    breadcrumbLabel: "Breadcrumb",
    cancel: "Cancel",
    close: "Close",
    currentRevision: "Current revision",
    back: "Back",
    checking: "Checking…",
    project: "Project",
  },
  navigation: {
    brandLabel: "JL Mixing Studio",
    primaryLabel: "Primary navigation",
    currentWorkspace: "Current workspace",
    defaultWorkspace: "Default workspace",
    checking: "Checking…",
    unavailable: "Unavailable",
    globalSearchLabel: "Global search",
    globalSearchPlaceholder: "Search everything",
  },
  workspace: {
    issueAttentionSingular: "item needs",
    issueAttentionPlural: "items need",
    issueAttentionSuffix: "attention",
    partialHelp: "Your available clients and projects are still here below.",
    reviewIssues: "Review issues",
    setupKicker: "Setup required",
    setupTitle: "Your studio workspace isn’t ready yet",
    setupBody: "Set up your studio workspace to get started.",
    invalidKicker: "Something doesn’t look right",
    invalidTitle: "We can’t read this studio setup yet",
    invalidBody: "Check the details below, then try again.",
    emptyKicker: "You’re ready to go",
    emptyTitle: "Your studio is ready for its first client",
    emptyBodyPrefix: "Choose",
    emptyBodyAction: "New client",
    emptyBodySuffix: "when you’re ready to get started.",
    issuesKicker: "A few things to check",
    issuesTitle: "Workspace issues",
    fallbackIssueName: "Workspace",
  },
  routes: {
    dashboard: { label: "Dashboard", eyebrow: "Studio overview", title: "What’s happening today?", description: "Here’s what’s happening in the studio and what needs your attention next." },
    studio: { label: "Studio", eyebrow: "Your studio", title: "Studio", description: "Your studio details, mix defaults, workspace, and tools—all in one place." },
    clients: { label: "Clients", eyebrow: "Who you’re working with", title: "Clients", description: "Find a client, check their defaults, or jump into a project." },
    projects: { label: "Projects", eyebrow: "What you’re working on", title: "Projects", description: "See every project and where each mix stands." },
    tasks: { label: "Tasks", eyebrow: "Up next", title: "Tasks", description: "A quick look at what needs your attention." },
    reports: { label: "Reports", eyebrow: "Project reports", title: "Reports", description: "Find intake, delivery, and other project reports in one place." },
    activity: { label: "Activity Log", eyebrow: "Recent activity", title: "Activity Log", description: "See the latest project updates across the studio." },
    settings: { label: "Settings", eyebrow: "Make it yours", title: "Settings", description: "Adjust how JL Mixing Studio looks and behaves." },
  },
  studio: {
    readingWorkspace: "Reading studio workspace…",
    workspaceUnavailable: "Studio workspace unavailable",
    tryAgain: "Try again",
    notConfigured: "Not configured",
    recoveryRequired: "Recovery required",
    createDefaultWorkspace: "Create the default studio workspace",
    configurationUnreadable: "Studio configuration is not readable",
    guidedSetupPrefix: "Use guided setup to create your studio workspace at",
    checkSetupIssues: "Check the setup issues below before making changes.",
    newStudio: "New studio",
    yourStudio: "Your studio",
    identity: "Studio Details",
    studioId: "Studio ID",
    mixEngineer: "Mix engineer",
    created: "Created",
    audioDefaults: "Mix Defaults",
    sampleRate: "Sample rate",
    bitDepth: "Bit depth",
    format: "Format",
    deliveryDefaults: "Delivery defaults",
    method: "Method",
    deliverables: "Deliverables",
    none: "None",
    workspaceTools: "Workspace & tools",
    workspace: "Workspace",
    configuredRoot: "Workspace Location",
    schema: "Schema",
    createdWith: "Created with",
    automation: "Automation",
    checkUnavailable: "Check unavailable",
    openWorkspace: "Open workspace",
    guidedSetup: "Guided setup",
    confirmNewStudio: "Confirm new studio",
    creationVerification: "Creation needs verification",
    newStudioTitle: "New studio",
    createWorkspacePrefix: "Creates your studio workspace at",
    standardLocationSuffix: "This setup uses the standard location.",
    studioName: "Studio name",
    optional: "(optional)",
    fileFormat: "File format",
    reviewStudio: "Review studio",
    confirmationIntro: "Nothing has been created yet. Confirm to create your studio workspace at the standard location.",
    studioLabel: "Studio",
    engineer: "Engineer",
    audio: "Audio",
    location: "Location",
    creating: "Creating…",
    createStudio: "Create studio",
    uncertainHelp: "Do not create the studio again automatically. Close this message, refresh Studio, and verify the workspace before trying again.",
  },
  settings: {
    kicker: "Studio preferences",
    title: "Settings",
    appearance: "Appearance",
    compactLayout: "Compact layout",
    compactLayoutHelp: "Reduce spacing in the application shell and data panels.",
    reduceMotion: "Reduce motion",
    reduceMotionHelp: "Disable interface scrolling and transition animation.",
    diagnostics: "Read-only diagnostics",
    workspace: "Workspace",
    workspaceStatus: "Workspace status",
    unavailable: "Unavailable",
    automation: "Automation",
    checkUnavailable: "Check unavailable",
    supportedContract: "Supported contract",
    boundary: "Settings boundary",
    boundaryPrefix: "These preferences are local to JL Mixing Studio. They do not edit",
    boundarySuffix: "client or project metadata, delivery defaults, or JL Mixing Automation.",
  },
  clients: {
    reading: "Reading clients…",
    loadFailed: "Clients could not be loaded",
    studioKicker: "Your studio",
    singular: "client",
    plural: "clients",
    newClient: "New client",
    searchLabel: "Clients",
    tableClient: "Client",
    tableClientId: "Client ID",
    tableDefaultArtist: "Default artist",
    tableProjects: "Projects",
    detailsLabel: "Client details",
    readOnly: "Read only",
    editingUnavailable: "Client editing isn’t available yet.",
    projectsKicker: "Client projects",
    projectsFor: "Projects for",
    editClient: "Edit client",
    newProject: "New project",
    noProjects: "No projects for this client.",
    createFirstProject: "Create the first project when you’re ready.",
    guidedSetup: "Guided setup",
    confirmNewClient: "Confirm new client",
    creationVerification: "Creation needs verification",
    inheritDefaults: "Audio and delivery settings will inherit the current studio defaults.",
    clientId: "Client ID",
    clientIdHelp: "Lowercase letters and numbers separated by single hyphens.",
    displayName: "Display name",
    defaultArtist: "Default artist",
    optional: "(optional)",
    reviewClient: "Review client",
    confirmationIntro: "Preflight passed without changing the workspace. Confirm to create this client.",
    creating: "Creating…",
    createClient: "Create client",
    uncertainHelp: "Do not submit the request again automatically. Close this message and use Refresh to inspect the workspace.",
  },
  projects: {
    reading: "Reading projects…",
    loadFailed: "Projects could not be loaded",
    studioKicker: "Your studio",
    singular: "project",
    plural: "projects",
    newProject: "New project",
    searchLabel: "Projects",
    tableProject: "Project",
    tableClient: "Client",
    tableArtist: "Artist",
    current: "Current",
    approved: "Approved",
    delivered: "Delivered",
    revisionPrefix: "Revision",
    tabs: { overview: "Overview", intake: "Intake", revisions: "Revisions", delivery: "Delivery", reports: "Reports", files: "Files", metadata: "Metadata" },
    workflowLabel: "Project workflow",
    revisionStateLabel: "Project revision state",
    informationKicker: "Project information",
    detailsTitle: "Project details",
    projectId: "Project ID",
    deadline: "Deadline",
    audio: "Audio",
    schema: "Schema",
    createdWith: "Created with",
    actionsKicker: "Project actions",
    actionsTitle: "Keep the project moving",
    openDawPlanned: "Open DAW — Planned",
    validateIntake: "Validate intake",
    newRevision: "New revision",
    viewRevisions: "View revisions",
    guidedSetup: "Guided setup",
    confirmNewProject: "Confirm new project",
    creationVerification: "Creation needs verification",
    inheritDefaults: "Audio and delivery settings inherit the selected client and studio defaults. Revision 1 is created automatically.",
    client: "Client",
    selectClient: "Select a client",
    currentClientHelp: "This project will be created for the current client.",
    projectName: "Project name",
    projectIdHelp: "JL Mixing Automation derives the stable project ID.",
    artist: "Artist",
    optional: "(optional)",
    useClientDefault: "Use the client default",
    reviewProject: "Review project",
    confirmationIntro: "Preflight passed without changing the workspace. Confirm to create this project and Revision 1.",
    initialRevision: "Initial revision",
    creating: "Creating…",
    createProject: "Create project",
    uncertainHelp: "Do not submit the request again automatically. Close this message and use Refresh to inspect the workspace.",
  },
  intake: {
    guided: "Guided validation",
    verificationTitle: "Validation needs verification",
    confirmTitle: "Confirm intake report update",
    uncertainHelp: "Do not run intake validation again automatically. Close this message, refresh Intake, and verify the report before trying again.",
    previewIntroPrefix: "The preview below did not change the project. Confirm to update only the generated section of",
    previewIntroSuffix: "Your intake source files will not be changed.",
    updating: "Updating report…",
    update: "Update intake report",
  },
  revision: {
    guided: "Guided revision",
    confirmTitle: "Confirm new revision",
    verificationTitle: "Creation needs verification",
    newTitle: "New revision",
    introPrefix: "Create the next revision for",
    introSuffix: "JL Mixing Studio will create the next revision number, folder, ID, timestamp, and notes file.",
    description: "Revision description",
    optional: "(optional)",
    descriptionHelp: "Leave blank to use the default description. Source files are still added manually.",
    review: "Review revision",
    confirmationIntro: "Nothing has changed yet. Confirm to create one new revision. The currently approved and delivered revisions will stay unchanged.",
    newRevision: "New revision",
    descriptionLabel: "Description",
    creating: "Creating…",
    create: "Create revision",
    uncertainHelp: "Do not create another revision automatically. Close this message, refresh Revisions, and verify the result before trying again.",
  },
  approval: {
    guided: "Guided approval",
    confirmTitle: "Confirm revision approval",
    verificationTitle: "Approval needs verification",
    approvePrefix: "Approve Revision",
    introPrefix: "Record approval for",
    introConnector: "of",
    introSuffix: "The current time will be recorded when you confirm the approval.",
    approvedBy: "Approved by",
    approvedByHelp: "This name is saved with the project approval.",
    review: "Review approval",
    confirmationIntro: "Nothing has changed yet. Confirm to make the selected revision the approved revision and save the new approval details.",
    selectedRevision: "Selected revision",
    currentApprovedRevision: "Current approved revision",
    none: "None",
    approvalTime: "Approval time",
    currentTimeAtExecution: "Current time at execution",
    checkChanges: "Check what will change",
    existingApprovalSuffix: "has an existing approval record that will be replaced.",
    olderThanCurrentConnector: "is older than current",
    deliveryRemainsPrefix: "The existing delivery remains on",
    approving: "Approving…",
    approve: "Approve revision",
    uncertainHelp: "Do not approve the revision again automatically. Close this message, refresh Revisions, and verify the result before trying again.",
  },
  delivery: {
    guided: "Guided delivery",
    createPackage: "Create delivery package",
    rebuildPackage: "Rebuild delivery package",
    replacementMode: "Replacement mode",
    samePathOverwrite: "Same-path overwrite",
    cleanReplacement: "Clean replacement",
    deliveryNotes: "Delivery Notes",
    createZip: "Create delivery ZIP",
    nonDestructiveReplacement: "Non-destructive replacement",
    destructiveReplacement: "Destructive replacement.",
    cancel: "Cancel",
    previewPackage: "Preview package",
    needsVerification: "Delivery needs verification",
    confirmPackage: "Confirm delivery package",
    close: "Close",
    approvedRevision: "Approved revision",
    currentRevision: "Current revision",
    deliveryMethod: "Delivery method",
    files: "Files",
    zip: "ZIP",
    source: "Source",
    type: "Type",
    destination: "Destination",
    notIncluded: "Not included in this delivery",
    deleteItems: "These items will be deleted",
    cleanConfirmationLabel: "Clean replacement confirmation",
    whatWillChange: "What will change",
    creating: "Creating…",
    cleanAndRebuild: "Clean and rebuild delivery",
    rebuildDelivery: "Rebuild delivery",
    createDelivery: "Create delivery",
    overwriteModeSummary: "Overwrite — same delivered path set only",
    overwriteModeShort: "Overwrite — same path set",
    cleanModeSummary: "Clean — delete all existing contents",
    firstPackageSummary: "None — first package",
    notesDeleted: "Deleted and recreated from template",
    notesPreserved: "Preserved",
    notesCreated: "Created from the standard delivery template",
    zipNotCreated: "Not created",
  },
  activity: {
    priority: { recovery: "Recovery", overdue: "Overdue", delivery: "Delivery", upcoming: "Upcoming", review: "Review" },
    event: { clientCreated: "Client created", projectCreated: "Project created", revisionCreated: "Revision created", revisionApproved: "Revision approved", deliveryCreated: "Delivery created" },
    deadlinePrefix: "Deadline",
    revisionPrefix: "Revision",
    openProject: "Open project",
  },
} as const;